#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/tbg28/neuron_install/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/tbg28/neuron_install/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/tbg28/git_staging/Sharp_Wave_2_Cell/Scripts_NEURON/x86_64/.libs/libnrnmech.so" "$@"
