#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/cluster/software/nrn-mpi/nrn-mpi-7.4"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/cluster/software/nrn-mpi/nrn-mpi-7.4/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/latimerb/data/Sharp_Wave_BLA/Single Cells/x86_64/.libs/libnrnmech.so" "$@"
